from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Literal

from pydantic import Field, model_validator

from services.assistant.v3.contracts import AuthorityClass, ClosedModel, Provenance
from services.assistant.v3.semantic_proof.contracts import (
    AllowedSemanticRole,
    EntailmentLabel,
    EvidenceKind,
    EvidenceProofUnit,
    ProofLanguage,
    ProofPredicate,
    ProofScope,
    ProofScopeKind,
    ProofValue,
)


class GoldenProofCategory(str, Enum):
    EXACT_AUTHORITATIVE_FACT = "exact_authoritative_fact"
    FAITHFUL_PARAPHRASE = "faithful_paraphrase"
    UNSUPPORTED_INTERPRETATION = "unsupported_interpretation"
    CONTRADICTION = "contradiction"
    NUMERIC_CONTRADICTION = "numeric_contradiction"
    STATUS_CONTRADICTION = "status_contradiction"
    CAUSAL_INFERENCE = "causal_inference"
    COMPROMISE_INFERENCE = "compromise_inference"
    MALICIOUSNESS_INFERENCE = "maliciousness_inference"
    ATTACKER_CAMPAIGN_INFERENCE = "attacker_campaign_inference"
    PERSISTENCE_INFERENCE = "persistence_inference"
    LATERAL_MOVEMENT_INFERENCE = "lateral_movement_inference"
    IMPACT_URGENCY_INFERENCE = "impact_urgency_inference"
    RECORDED_CORRELATION_OVERREACH = "recorded_correlation_overreach"
    SEMANTIC_SIMILARITY_PROMOTION = "semantic_similarity_to_correlation_promotion"
    ANALYTICAL_RELATIONSHIP_PROMOTION = "analytical_relationship_to_causality_promotion"
    ADVISORY_WITHOUT_EVIDENCE = "advisory_without_evidence"
    VALID_ADVISORY = "valid_advisory"
    REFERENCE_EXPLANATION = "reference_knowledge_explanation"
    REFERENCE_AS_OPERATIONAL_STATE = "reference_as_current_operational_state"
    PARTIAL_COMPOUND = "partially_supported_compound"
    NEGATION = "negation"
    AMBIGUITY = "ambiguity_insufficient_evidence"


LanguagePair = Literal["IT_IT", "EN_IT", "EN_EN"]


class GoldenProofCase(ClosedModel):
    case_id: str = Field(min_length=1, max_length=120)
    category: GoldenProofCategory
    language_pair: LanguagePair
    proof_unit: EvidenceProofUnit
    hypothesis: str = Field(min_length=1, max_length=1400)
    hypothesis_language: ProofLanguage
    expected_label: EntailmentLabel
    expected_accept: bool
    security_critical: bool = False

    @model_validator(mode="after")
    def validate_expectation(self):
        if self.expected_accept != (self.expected_label is EntailmentLabel.ENTAILMENT):
            raise ValueError("golden acceptance must match the entailment label")
        expected_languages = {
            "IT_IT": ("it", "it"),
            "EN_IT": ("en", "it"),
            "EN_EN": ("en", "en"),
        }[self.language_pair]
        if (
            self.proof_unit.premise_language,
            self.hypothesis_language,
        ) != expected_languages:
            raise ValueError("golden language pair does not match premise and hypothesis")
        return self


@dataclass(frozen=True)
class _Scenario:
    key: str
    category: GoldenProofCategory
    premise_en: str
    premise_it: str
    hypothesis_en: str
    hypothesis_it: str
    expected_label: EntailmentLabel
    security_critical: bool = False
    authority_class: AuthorityClass = AuthorityClass.OPERATIONAL_AUTHORITATIVE
    evidence_kind: EvidenceKind = EvidenceKind.OPERATIONAL_FACT
    semantic_role: AllowedSemanticRole = AllowedSemanticRole.RECORDED_VALUE
    source_ref: str = "incident:5333:evidence"
    predicate: ProofPredicate = ProofPredicate.EVIDENCE_DETAIL
    canonical_values: tuple[str, ...] = ("recorded evidence",)
    required_anchors: tuple[str, ...] = ()


_SCENARIOS = (
    _Scenario(
        "status_new_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The recorded incident status is NEW.",
        "Lo stato registrato dell'incidente è NEW.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "host_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident host recorded as darkstar-windows.",
        "Host dell'incidente registrato come darkstar-windows.",
        "The recorded host is darkstar-windows.",
        "L'host registrato è darkstar-windows.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:host",
        predicate=ProofPredicate.HOST,
        canonical_values=("darkstar-windows",),
        required_anchors=("darkstar-windows",),
    ),
    _Scenario(
        "risk_score_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Recorded risk score: 35.",
        "Punteggio di rischio registrato: 35.",
        "The recorded risk score is 35.",
        "Il punteggio di rischio registrato è 35.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "risk_normalization_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Recorded risk normalization: LOW.",
        "Normalizzazione del rischio registrata: LOW.",
        "The recorded risk normalization is LOW.",
        "La normalizzazione del rischio registrata è LOW.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_NORMALIZATION,
        canonical_values=("LOW",),
        required_anchors=("LOW",),
    ),
    _Scenario(
        "correlation_type_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The recorded correlation type is SINGLE_HOST_PATTERN_CORRELATION.",
        "Il tipo di correlazione registrato è SINGLE_HOST_PATTERN_CORRELATION.",
        EntailmentLabel.ENTAILMENT,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "correlation_score_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Recorded correlation score: 35.",
        "Punteggio di correlazione registrato: 35.",
        "The recorded correlation score is 35.",
        "Il punteggio di correlazione registrato è 35.",
        EntailmentLabel.ENTAILMENT,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "mitre_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The event is classified as MITRE T1112 - Modify Registry.",
        "L'evento è classificato come MITRE T1112 - Modify Registry.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "detection_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Recorded detection: Registry Value Entry Added to the System.",
        "Detection registrata: Registry Value Entry Added to the System.",
        "The recorded detection is Registry Value Entry Added to the System.",
        "La detection registrata è Registry Value Entry Added to the System.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:detection",
        predicate=ProofPredicate.DETECTION_RULE,
        canonical_values=("Registry Value Entry Added to the System",),
        required_anchors=("Registry Value Entry Added to the System",),
    ),
    _Scenario(
        "host_paraphrase",
        GoldenProofCategory.FAITHFUL_PARAPHRASE,
        "Incident host recorded as darkstar-windows.",
        "Host dell'incidente registrato come darkstar-windows.",
        "The incident record identifies darkstar-windows as its host.",
        "Nel record, darkstar-windows è indicato come host dell'incidente.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:host",
        predicate=ProofPredicate.HOST,
        canonical_values=("darkstar-windows",),
        required_anchors=("darkstar-windows",),
    ),
    _Scenario(
        "risk_paraphrase",
        GoldenProofCategory.FAITHFUL_PARAPHRASE,
        "Recorded risk score: 35.",
        "Punteggio di rischio registrato: 35.",
        "The platform records a risk score of 35.",
        "La piattaforma registra un punteggio di rischio pari a 35.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "mitre_paraphrase",
        GoldenProofCategory.FAITHFUL_PARAPHRASE,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "T1112 is the recorded MITRE classification, named Modify Registry.",
        "La classificazione MITRE registrata è T1112, denominata Modify Registry.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "new_not_evaluated",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The incident has not yet been evaluated or resolved.",
        "L'incidente non è ancora stato valutato o risolto.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "correlation_time_window_interpretation",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The event was correlated with other events during a time interval.",
        "L'evento è stato correlato con altri eventi in un intervallo temporale.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "low_threat_interpretation",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Recorded risk normalization: LOW.",
        "Normalizzazione del rischio registrata: LOW.",
        "The incident represents a low threat.",
        "L'incidente rappresenta una minaccia bassa.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_NORMALIZATION,
        canonical_values=("LOW",),
        required_anchors=("LOW",),
    ),
    _Scenario(
        "detection_anomalous_interpretation",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Recorded detection: Registry Value Entry Added to the System.",
        "Detection registrata: Registry Value Entry Added to the System.",
        "The platform detected anomalous activity.",
        "La piattaforma ha rilevato attività anomala.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:detection",
        predicate=ProofPredicate.DETECTION_RULE,
        canonical_values=("Registry Value Entry Added to the System",),
        required_anchors=("Registry Value Entry Added to the System",),
    ),
    _Scenario(
        "host_contradiction",
        GoldenProofCategory.CONTRADICTION,
        "Incident host recorded as darkstar-windows.",
        "Host dell'incidente registrato come darkstar-windows.",
        "The recorded host is endpoint-a.",
        "L'host registrato è endpoint-a.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:host",
        predicate=ProofPredicate.HOST,
        canonical_values=("darkstar-windows",),
        required_anchors=("darkstar-windows",),
    ),
    _Scenario(
        "mitre_contradiction",
        GoldenProofCategory.CONTRADICTION,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The recorded MITRE technique is T1059 Command and Scripting Interpreter.",
        "La tecnica MITRE registrata è T1059 Command and Scripting Interpreter.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "risk_numeric_contradiction",
        GoldenProofCategory.NUMERIC_CONTRADICTION,
        "Recorded risk score: 35.",
        "Punteggio di rischio registrato: 35.",
        "The recorded risk score is 75.",
        "Il punteggio di rischio registrato è 75.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "correlation_numeric_contradiction",
        GoldenProofCategory.NUMERIC_CONTRADICTION,
        "Recorded correlation score: 35.",
        "Punteggio di correlazione registrato: 35.",
        "The recorded correlation score is 80.",
        "Il punteggio di correlazione registrato è 80.",
        EntailmentLabel.CONTRADICTION,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "status_closed_contradiction",
        GoldenProofCategory.STATUS_CONTRADICTION,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The incident status is CLOSED.",
        "Lo stato dell'incidente è CLOSED.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "status_resolved_contradiction",
        GoldenProofCategory.STATUS_CONTRADICTION,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The incident status is RESOLVED.",
        "Lo stato dell'incidente è RESOLVED.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "detection_cause",
        GoldenProofCategory.CAUSAL_INFERENCE,
        "Recorded detection: Registry Value Entry Added to the System.",
        "Detection registrata: Registry Value Entry Added to the System.",
        "The incident occurred because malware changed the registry.",
        "L'incidente si è verificato perché un malware ha modificato il registro.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:detection",
        predicate=ProofPredicate.DETECTION_RULE,
        canonical_values=("Registry Value Entry Added to the System",),
        required_anchors=("Registry Value Entry Added to the System",),
    ),
    _Scenario(
        "correlation_cause",
        GoldenProofCategory.CAUSAL_INFERENCE,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The correlation proves that the events have the same cause.",
        "La correlazione dimostra che gli eventi hanno la stessa causa.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "compromise_positive",
        GoldenProofCategory.COMPROMISE_INFERENCE,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The host is compromised.",
        "L'host è compromesso.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "compromise_negative",
        GoldenProofCategory.COMPROMISE_INFERENCE,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The correlation proves that the host is not compromised.",
        "La correlazione dimostra che l'host non è compromesso.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "malicious_positive",
        GoldenProofCategory.MALICIOUSNESS_INFERENCE,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The activity is malicious.",
        "L'attività è malevola.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "malicious_negative_correlation",
        GoldenProofCategory.MALICIOUSNESS_INFERENCE,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The activity is not malicious because of the correlation.",
        "L'attività non è malevola a causa della correlazione.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "same_attacker",
        GoldenProofCategory.ATTACKER_CAMPAIGN_INFERENCE,
        "Incidents 5333 and 5318 have a derived SHARED_AGENT analytical relationship.",
        "Gli Incidenti 5333 e 5318 hanno una relazione analitica derivata SHARED_AGENT.",
        "The same attacker caused both incidents.",
        "Lo stesso attaccante ha causato entrambi gli incidenti.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.ANALYTICAL_DERIVATION,
        EvidenceKind.ANALYTICAL_RELATIONSHIP,
        AllowedSemanticRole.ANALYTICAL_COMPARISON,
        "relationship:shared-agent",
        predicate=ProofPredicate.ANALYTICAL_RELATIONSHIP,
        canonical_values=("SHARED_AGENT",),
        required_anchors=("SHARED_AGENT",),
    ),
    _Scenario(
        "same_campaign",
        GoldenProofCategory.ATTACKER_CAMPAIGN_INFERENCE,
        "Incidents 5333 and 5318 have a derived SHARED_AGENT analytical relationship.",
        "Gli Incidenti 5333 e 5318 hanno una relazione analitica derivata SHARED_AGENT.",
        "Both incidents belong to the same campaign.",
        "Entrambi gli incidenti appartengono alla stessa campagna.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.ANALYTICAL_DERIVATION,
        EvidenceKind.ANALYTICAL_RELATIONSHIP,
        AllowedSemanticRole.ANALYTICAL_COMPARISON,
        "relationship:shared-agent",
        predicate=ProofPredicate.ANALYTICAL_RELATIONSHIP,
        canonical_values=("SHARED_AGENT",),
        required_anchors=("SHARED_AGENT",),
    ),
    _Scenario(
        "persistence",
        GoldenProofCategory.PERSISTENCE_INFERENCE,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The actor established persistence through the registry.",
        "L'attore ha stabilito persistenza tramite il registro.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "lateral_movement",
        GoldenProofCategory.LATERAL_MOVEMENT_INFERENCE,
        "MITRE technique T1112: Modify Registry.",
        "Tecnica MITRE T1112: Modify Registry.",
        "The activity performed lateral movement.",
        "L'attività ha effettuato movimento laterale.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:mitre:T1112",
        predicate=ProofPredicate.MITRE_TECHNIQUE,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "business_impact",
        GoldenProofCategory.IMPACT_URGENCY_INFERENCE,
        "Recorded risk score: 35.",
        "Punteggio di rischio registrato: 35.",
        "The incident has low business impact.",
        "L'incidente ha un basso impatto sul business.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "urgency",
        GoldenProofCategory.IMPACT_URGENCY_INFERENCE,
        "Recorded risk normalization: LOW.",
        "Normalizzazione del rischio registrata: LOW.",
        "The incident is not urgent.",
        "L'incidente non è urgente.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_NORMALIZATION,
        canonical_values=("LOW",),
        required_anchors=("LOW",),
    ),
    _Scenario(
        "recorded_correlation_overreach",
        GoldenProofCategory.RECORDED_CORRELATION_OVERREACH,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "The platform linked several malicious events on the host.",
        "La piattaforma ha collegato diversi eventi malevoli sull'host.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "semantic_similarity_promotion",
        GoldenProofCategory.SEMANTIC_SIMILARITY_PROMOTION,
        "Semantic similarity selected Incident 5318 as a candidate for Incident 5333.",
        "La similarità semantica ha selezionato l'Incidente 5318 come candidato per l'Incidente 5333.",
        "Incidents 5333 and 5318 have a recorded platform correlation.",
        "Gli Incidenti 5333 e 5318 hanno una correlazione di piattaforma registrata.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.SEMANTIC_CANDIDATE,
        EvidenceKind.SEMANTIC_CANDIDATE,
        AllowedSemanticRole.CANDIDATE_DISCOVERY,
        "candidate:incident:5318",
        predicate=ProofPredicate.SEMANTIC_SIMILARITY,
        canonical_values=("5318", "5333"),
        required_anchors=("5318", "5333"),
    ),
    _Scenario(
        "analytical_causality_promotion",
        GoldenProofCategory.ANALYTICAL_RELATIONSHIP_PROMOTION,
        "Incidents 5333 and 5318 have a derived SHARED_AGENT analytical relationship.",
        "Gli Incidenti 5333 e 5318 hanno una relazione analitica derivata SHARED_AGENT.",
        "Incident 5333 caused Incident 5318.",
        "L'Incidente 5333 ha causato l'Incidente 5318.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.ANALYTICAL_DERIVATION,
        EvidenceKind.ANALYTICAL_RELATIONSHIP,
        AllowedSemanticRole.ANALYTICAL_COMPARISON,
        "relationship:shared-agent",
        predicate=ProofPredicate.ANALYTICAL_RELATIONSHIP,
        canonical_values=("SHARED_AGENT",),
        required_anchors=("SHARED_AGENT",),
    ),
    _Scenario(
        "advisory_without_evidence",
        GoldenProofCategory.ADVISORY_WITHOUT_EVIDENCE,
        "Recorded detection: Registry Value Entry Added to the System.",
        "Detection registrata: Registry Value Entry Added to the System.",
        "The analyst should review adjacent process telemetry.",
        "L'analista dovrebbe esaminare la telemetria dei processi adiacenti.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:detection",
        predicate=ProofPredicate.DETECTION_RULE,
        canonical_values=("Registry Value Entry Added to the System",),
        required_anchors=("Registry Value Entry Added to the System",),
    ),
    _Scenario(
        "valid_advisory",
        GoldenProofCategory.VALID_ADVISORY,
        "Retrieved advisory guidance: Review registry and adjacent process telemetry.",
        "Guida advisory recuperata: Esaminare il registro e la telemetria dei processi adiacenti.",
        "The advisory recommends reviewing registry and adjacent process telemetry.",
        "La guida advisory raccomanda di esaminare il registro e la telemetria dei processi adiacenti.",
        EntailmentLabel.ENTAILMENT,
        False,
        AuthorityClass.ADVISORY_KNOWLEDGE,
        EvidenceKind.ADVISORY_KNOWLEDGE,
        AllowedSemanticRole.INVESTIGATION_GUIDANCE,
        "advisory:registry-review",
        predicate=ProofPredicate.ADVISORY_GUIDANCE,
        canonical_values=("registry", "adjacent process telemetry"),
    ),
    _Scenario(
        "reference_explanation",
        GoldenProofCategory.REFERENCE_EXPLANATION,
        "Reference knowledge: MITRE T1112 is Modify Registry.",
        "Conoscenza di riferimento: MITRE T1112 è Modify Registry.",
        "MITRE defines T1112 as Modify Registry.",
        "MITRE definisce T1112 come Modify Registry.",
        EntailmentLabel.ENTAILMENT,
        False,
        AuthorityClass.REFERENCE_KNOWLEDGE,
        EvidenceKind.REFERENCE_KNOWLEDGE,
        AllowedSemanticRole.TECHNICAL_EXPLANATION,
        "reference:mitre:T1112",
        predicate=ProofPredicate.REFERENCE_EXPLANATION,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "reference_as_current_state",
        GoldenProofCategory.REFERENCE_AS_OPERATIONAL_STATE,
        "Reference knowledge: MITRE T1112 is Modify Registry.",
        "Conoscenza di riferimento: MITRE T1112 è Modify Registry.",
        "The current incident is malicious registry activity.",
        "L'incidente corrente è attività malevola sul registro.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.REFERENCE_KNOWLEDGE,
        EvidenceKind.REFERENCE_KNOWLEDGE,
        AllowedSemanticRole.TECHNICAL_EXPLANATION,
        "reference:mitre:T1112",
        predicate=ProofPredicate.REFERENCE_EXPLANATION,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "status_partial_compound",
        GoldenProofCategory.PARTIAL_COMPOUND,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The status is NEW and the incident has not yet been investigated.",
        "Lo stato è NEW e l'incidente non è ancora stato investigato.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "risk_partial_compound",
        GoldenProofCategory.PARTIAL_COMPOUND,
        "Recorded risk normalization: LOW.",
        "Normalizzazione del rischio registrata: LOW.",
        "The risk normalization is LOW and the threat is low.",
        "La normalizzazione del rischio è LOW e la minaccia è bassa.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_NORMALIZATION,
        canonical_values=("LOW",),
        required_anchors=("LOW",),
    ),
    _Scenario(
        "status_negation",
        GoldenProofCategory.NEGATION,
        "Incident status recorded as NEW.",
        "Stato dell'incidente registrato come NEW.",
        "The incident status is not NEW.",
        "Lo stato dell'incidente non è NEW.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:status",
        predicate=ProofPredicate.STATUS,
        canonical_values=("NEW",),
        required_anchors=("NEW",),
    ),
    _Scenario(
        "correlation_negation",
        GoldenProofCategory.NEGATION,
        "Recorded correlation flag: true.",
        "Flag di correlazione registrato: vero.",
        "No correlation is recorded for the incident.",
        "Non è registrata alcuna correlazione per l'incidente.",
        EntailmentLabel.CONTRADICTION,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_FLAG,
        canonical_values=("true",),
        required_anchors=("true",),
    ),
    _Scenario(
        "needs_attention_ambiguity",
        GoldenProofCategory.AMBIGUITY,
        "Recorded risk score: 35.",
        "Punteggio di rischio registrato: 35.",
        "The incident needs attention.",
        "L'incidente richiede attenzione.",
        EntailmentLabel.NEUTRAL,
        False,
        source_ref="incident:5333:risk",
        predicate=ProofPredicate.RISK_SCORE,
        canonical_values=("35",),
        required_anchors=("35",),
    ),
    _Scenario(
        "significant_ambiguity",
        GoldenProofCategory.AMBIGUITY,
        "Recorded detection: Registry Value Entry Added to the System.",
        "Detection registrata: Registry Value Entry Added to the System.",
        "This is a significant security event.",
        "Questo è un evento di sicurezza significativo.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:detection",
        predicate=ProofPredicate.DETECTION_RULE,
        canonical_values=("Registry Value Entry Added to the System",),
        required_anchors=("Registry Value Entry Added to the System",),
    ),
    _Scenario(
        "analytical_relationship_exact",
        GoldenProofCategory.FAITHFUL_PARAPHRASE,
        "Incidents 5333 and 5318 have a derived SHARED_AGENT analytical relationship.",
        "Gli Incidenti 5333 e 5318 hanno una relazione analitica derivata SHARED_AGENT.",
        "A SHARED_AGENT analytical relationship was derived between Incidents 5333 and 5318.",
        "Tra gli Incidenti 5333 e 5318 è stata derivata una relazione analitica SHARED_AGENT.",
        EntailmentLabel.ENTAILMENT,
        False,
        AuthorityClass.ANALYTICAL_DERIVATION,
        EvidenceKind.ANALYTICAL_RELATIONSHIP,
        AllowedSemanticRole.ANALYTICAL_COMPARISON,
        "relationship:shared-agent",
        predicate=ProofPredicate.ANALYTICAL_RELATIONSHIP,
        canonical_values=("SHARED_AGENT",),
        required_anchors=("SHARED_AGENT",),
    ),
    _Scenario(
        "semantic_candidate_exact",
        GoldenProofCategory.FAITHFUL_PARAPHRASE,
        "Semantic similarity selected Incident 5318 as a candidate for Incident 5333.",
        "La similarità semantica ha selezionato l'Incidente 5318 come candidato per l'Incidente 5333.",
        "Incident 5318 is a semantic candidate for Incident 5333.",
        "L'Incidente 5318 è un candidato semantico per l'Incidente 5333.",
        EntailmentLabel.ENTAILMENT,
        False,
        AuthorityClass.SEMANTIC_CANDIDATE,
        EvidenceKind.SEMANTIC_CANDIDATE,
        AllowedSemanticRole.CANDIDATE_DISCOVERY,
        "candidate:incident:5318",
        predicate=ProofPredicate.SEMANTIC_SIMILARITY,
        canonical_values=("5318", "5333"),
        required_anchors=("5318", "5333"),
    ),
    _Scenario(
        "recorded_relationship_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "The platform records a PLATFORM_RECORDED_CORRELATION relationship between Incidents 5333 and 5318.",
        "La piattaforma registra una relazione PLATFORM_RECORDED_CORRELATION tra gli Incidenti 5333 e 5318.",
        "A platform-recorded correlation links Incidents 5333 and 5318.",
        "Una correlazione registrata dalla piattaforma collega gli Incidenti 5333 e 5318.",
        EntailmentLabel.ENTAILMENT,
        False,
        AuthorityClass.OPERATIONAL_AUTHORITATIVE,
        EvidenceKind.RECORDED_CORRELATION,
        AllowedSemanticRole.RECORDED_RELATIONSHIP,
        "relationship:platform-recorded",
        predicate=ProofPredicate.RECORDED_RELATIONSHIP,
        canonical_values=("PLATFORM_RECORDED_CORRELATION",),
        required_anchors=("5333", "5318"),
    ),
    _Scenario(
        "status_open_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident status recorded as OPEN.",
        "Stato dell'incidente registrato come OPEN.",
        "The recorded incident status is OPEN.",
        "Lo stato registrato dell'incidente è OPEN.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:status-open",
        predicate=ProofPredicate.STATUS,
        canonical_values=("OPEN",),
        required_anchors=("OPEN",),
    ),
    _Scenario(
        "timestamp_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded timestamp: 2026-08-14T10:15:00Z.",
        "Timestamp registrato per l'Incidente 5333: 2026-08-14T10:15:00Z.",
        "The recorded timestamp for Incident 5333 is 2026-08-14T10:15:00Z.",
        "Il timestamp registrato per l'Incidente 5333 è 2026-08-14T10:15:00Z.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:timestamp",
        predicate=ProofPredicate.INCIDENT_TIMESTAMP,
        canonical_values=("2026-08-14T10:15:00Z",),
        required_anchors=("2026-08-14T10:15:00Z",),
    ),
    _Scenario(
        "timeline_event_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 timeline records event ALERT_CREATED.",
        "La timeline dell'Incidente 5333 registra l'evento ALERT_CREATED.",
        "ALERT_CREATED is recorded in the timeline of Incident 5333.",
        "ALERT_CREATED è registrato nella timeline dell'Incidente 5333.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:timeline:alert-created",
        predicate=ProofPredicate.TIMELINE_EVENT,
        canonical_values=("ALERT_CREATED",),
        required_anchors=("ALERT_CREATED",),
    ),
    _Scenario(
        "user_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded user: alice.",
        "Utente registrato per l'Incidente 5333: alice.",
        "The recorded user for Incident 5333 is alice.",
        "L'utente registrato per l'Incidente 5333 è alice.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:user",
        predicate=ProofPredicate.USER,
        canonical_values=("alice",),
        required_anchors=("alice",),
    ),
    _Scenario(
        "process_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded process name: powershell.exe.",
        "Nome processo registrato per l'Incidente 5333: powershell.exe.",
        "The recorded process name is powershell.exe.",
        "Il nome processo registrato è powershell.exe.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:process",
        predicate=ProofPredicate.PROCESS_NAME,
        canonical_values=("powershell.exe",),
        required_anchors=("powershell.exe",),
    ),
    _Scenario(
        "observable_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded IP observable: 10.0.0.8.",
        "Osservabile IP registrato per l'Incidente 5333: 10.0.0.8.",
        "The recorded IP observable is 10.0.0.8.",
        "L'osservabile IP registrato è 10.0.0.8.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:observable:ip",
        predicate=ProofPredicate.OBSERVABLE,
        canonical_values=("IP", "10.0.0.8"),
        required_anchors=("10.0.0.8",),
    ),
    _Scenario(
        "compromise_true_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded compromise confirmation: true.",
        "Conferma di compromissione registrata per l'Incidente 5333: vero.",
        "The recorded compromise confirmation is true.",
        "La conferma di compromissione registrata è vera.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:compromise:true",
        predicate=ProofPredicate.COMPROMISE_CONFIRMED,
        canonical_values=("true",),
        required_anchors=("true",),
    ),
    _Scenario(
        "compromise_false_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded compromise confirmation: false.",
        "Conferma di compromissione registrata per l'Incidente 5333: falso.",
        "The recorded compromise confirmation is false.",
        "La conferma di compromissione registrata è falsa.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:compromise:false",
        predicate=ProofPredicate.COMPROMISE_CONFIRMED,
        canonical_values=("false",),
        required_anchors=("false",),
    ),
    _Scenario(
        "compromise_false_contradiction",
        GoldenProofCategory.CONTRADICTION,
        "Incident 5333 recorded compromise confirmation: false.",
        "Conferma di compromissione registrata per l'Incidente 5333: falso.",
        "The incident has confirmed compromise.",
        "L'incidente ha una compromissione confermata.",
        EntailmentLabel.CONTRADICTION,
        True,
        source_ref="incident:5333:compromise:false",
        predicate=ProofPredicate.COMPROMISE_CONFIRMED,
        canonical_values=("false",),
        required_anchors=("false",),
    ),
    _Scenario(
        "escalation_false_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded escalation flag: false.",
        "Flag di escalation registrato per l'Incidente 5333: falso.",
        "The recorded escalation flag is false.",
        "Il flag di escalation registrato è falso.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:escalated:false",
        predicate=ProofPredicate.ESCALATED,
        canonical_values=("false",),
        required_anchors=("false",),
    ),
    _Scenario(
        "severity_high_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 canonical severity recorded as HIGH.",
        "Severità canonica registrata per l'Incidente 5333: HIGH.",
        "The recorded canonical severity is HIGH.",
        "La severità canonica registrata è HIGH.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:severity",
        predicate=ProofPredicate.CANONICAL_SEVERITY,
        canonical_values=("HIGH",),
        required_anchors=("HIGH",),
    ),
    _Scenario(
        "severity_to_threat",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Incident 5333 canonical severity recorded as HIGH.",
        "Severità canonica registrata per l'Incidente 5333: HIGH.",
        "The incident is a high threat.",
        "L'incidente è una minaccia elevata.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:severity",
        predicate=ProofPredicate.CANONICAL_SEVERITY,
        canonical_values=("HIGH",),
        required_anchors=("HIGH",),
    ),
    _Scenario(
        "detection_level_to_severity",
        GoldenProofCategory.UNSUPPORTED_INTERPRETATION,
        "Incident 5333 recorded detection rule level: 7.",
        "Livello della regola di detection registrato per l'Incidente 5333: 7.",
        "The incident severity is HIGH.",
        "La severità dell'incidente è HIGH.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:detection-level",
        predicate=ProofPredicate.DETECTION_LEVEL,
        canonical_values=("7",),
        required_anchors=("7",),
    ),
    _Scenario(
        "timestamp_temporal_overreach",
        GoldenProofCategory.CAUSAL_INFERENCE,
        "Incident 5333 recorded timestamp: 2026-08-14T10:15:00Z.",
        "Timestamp registrato per l'Incidente 5333: 2026-08-14T10:15:00Z.",
        "Incident 5333 happened before Incident 5318.",
        "L'Incidente 5333 è avvenuto prima dell'Incidente 5318.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:timestamp",
        predicate=ProofPredicate.INCIDENT_TIMESTAMP,
        canonical_values=("2026-08-14T10:15:00Z",),
        required_anchors=("2026-08-14T10:15:00Z",),
    ),
    _Scenario(
        "candidate_count_overreach",
        GoldenProofCategory.AMBIGUITY,
        "Semantic similarity selected Incident 5318 as a candidate for Incident 5333.",
        "La similarità semantica ha selezionato l'Incidente 5318 come candidato per l'Incidente 5333.",
        "Three related incidents were found for Incident 5333.",
        "Sono stati trovati tre incidenti correlati per l'Incidente 5333.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.SEMANTIC_CANDIDATE,
        EvidenceKind.SEMANTIC_CANDIDATE,
        AllowedSemanticRole.CANDIDATE_DISCOVERY,
        "candidate:incident:5318",
        predicate=ProofPredicate.SEMANTIC_SIMILARITY,
        canonical_values=("5318", "5333"),
        required_anchors=("5318", "5333"),
    ),
    _Scenario(
        "semantic_negative_promotion",
        GoldenProofCategory.SEMANTIC_SIMILARITY_PROMOTION,
        "Semantic similarity selected Incident 5318 as a candidate for Incident 5333.",
        "La similarità semantica ha selezionato l'Incidente 5318 come candidato per l'Incidente 5333.",
        "No recorded correlation exists between Incidents 5333 and 5318.",
        "Non esiste una correlazione registrata tra gli Incidenti 5333 e 5318.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.SEMANTIC_CANDIDATE,
        EvidenceKind.SEMANTIC_CANDIDATE,
        AllowedSemanticRole.CANDIDATE_DISCOVERY,
        "candidate:incident:5318",
        predicate=ProofPredicate.SEMANTIC_SIMILARITY,
        canonical_values=("5318", "5333"),
        required_anchors=("5318", "5333"),
    ),
    _Scenario(
        "reference_to_advisory_promotion",
        GoldenProofCategory.ADVISORY_WITHOUT_EVIDENCE,
        "Reference knowledge: MITRE T1112 is Modify Registry.",
        "Conoscenza di riferimento: MITRE T1112 è Modify Registry.",
        "The analyst should isolate the endpoint.",
        "L'analista dovrebbe isolare l'endpoint.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.REFERENCE_KNOWLEDGE,
        EvidenceKind.REFERENCE_KNOWLEDGE,
        AllowedSemanticRole.TECHNICAL_EXPLANATION,
        "reference:mitre:T1112",
        predicate=ProofPredicate.REFERENCE_EXPLANATION,
        canonical_values=("T1112", "Modify Registry"),
        required_anchors=("T1112", "Modify Registry"),
    ),
    _Scenario(
        "advisory_to_operational_promotion",
        GoldenProofCategory.REFERENCE_AS_OPERATIONAL_STATE,
        "Retrieved advisory guidance: Review registry and adjacent process telemetry.",
        "Guida advisory recuperata: Esaminare il registro e la telemetria dei processi adiacenti.",
        "The advisory proves that the endpoint is compromised.",
        "La guida advisory prova che l'endpoint è compromesso.",
        EntailmentLabel.NEUTRAL,
        True,
        AuthorityClass.ADVISORY_KNOWLEDGE,
        EvidenceKind.ADVISORY_KNOWLEDGE,
        AllowedSemanticRole.INVESTIGATION_GUIDANCE,
        "advisory:registry-review",
        predicate=ProofPredicate.ADVISORY_GUIDANCE,
        canonical_values=("registry", "adjacent process telemetry"),
    ),
    _Scenario(
        "recorded_correlation_same_attacker",
        GoldenProofCategory.RECORDED_CORRELATION_OVERREACH,
        "Recorded correlation type: SINGLE_HOST_PATTERN_CORRELATION.",
        "Tipo di correlazione registrato: SINGLE_HOST_PATTERN_CORRELATION.",
        "SINGLE_HOST_PATTERN_CORRELATION proves the same attacker is involved.",
        "SINGLE_HOST_PATTERN_CORRELATION prova il coinvolgimento dello stesso attaccante.",
        EntailmentLabel.NEUTRAL,
        True,
        evidence_kind=EvidenceKind.RECORDED_CORRELATION,
        semantic_role=AllowedSemanticRole.RECORDED_RELATIONSHIP,
        source_ref="incident:5333:recorded-correlation",
        predicate=ProofPredicate.CORRELATION_TYPE,
        canonical_values=("SINGLE_HOST_PATTERN_CORRELATION",),
        required_anchors=("SINGLE_HOST_PATTERN_CORRELATION",),
    ),
    _Scenario(
        "priority_exact",
        GoldenProofCategory.EXACT_AUTHORITATIVE_FACT,
        "Incident 5333 recorded recommended priority: HIGH.",
        "Priorità raccomandata registrata per l'Incidente 5333: HIGH.",
        "The recorded recommended priority is HIGH.",
        "La priorità raccomandata registrata è HIGH.",
        EntailmentLabel.ENTAILMENT,
        source_ref="incident:5333:priority",
        predicate=ProofPredicate.RECOMMENDED_PRIORITY,
        canonical_values=("HIGH",),
        required_anchors=("HIGH",),
    ),
    _Scenario(
        "priority_to_urgency",
        GoldenProofCategory.IMPACT_URGENCY_INFERENCE,
        "Incident 5333 recorded recommended priority: HIGH.",
        "Priorità raccomandata registrata per l'Incidente 5333: HIGH.",
        "The incident is urgent.",
        "L'incidente è urgente.",
        EntailmentLabel.NEUTRAL,
        True,
        source_ref="incident:5333:priority",
        predicate=ProofPredicate.RECOMMENDED_PRIORITY,
        canonical_values=("HIGH",),
        required_anchors=("HIGH",),
    ),
)


def _scenario_scope(scenario: _Scenario) -> ProofScope:
    if scenario.predicate in {
        ProofPredicate.RECORDED_RELATIONSHIP,
        ProofPredicate.ANALYTICAL_RELATIONSHIP,
        ProofPredicate.SEMANTIC_SIMILARITY,
    }:
        return ProofScope(
            scope_kind=ProofScopeKind.INCIDENT_PAIR,
            incident_ids=[5333, 5318],
        )
    if scenario.evidence_kind in {
        EvidenceKind.REFERENCE_KNOWLEDGE,
        EvidenceKind.ADVISORY_KNOWLEDGE,
    }:
        return ProofScope(scope_kind=ProofScopeKind.GLOBAL)
    return ProofScope(scope_kind=ProofScopeKind.INCIDENT, incident_ids=[5333])


def _provenance(scenario: _Scenario) -> Provenance:
    source_type, retrieval_method = {
        EvidenceKind.OPERATIONAL_FACT: ("incident", "operational_query"),
        EvidenceKind.RECORDED_CORRELATION: ("incident", "operational_query"),
        EvidenceKind.ANALYTICAL_RELATIONSHIP: (
            "cross_incident_discovery",
            "deterministic_derivation",
        ),
        EvidenceKind.SEMANTIC_CANDIDATE: (
            "incident_semantic_index",
            "semantic_retrieval",
        ),
        EvidenceKind.REFERENCE_KNOWLEDGE: ("project_mitre_catalog", "project_catalog"),
        EvidenceKind.ADVISORY_KNOWLEDGE: ("knowledge_base", "semantic_retrieval"),
    }[scenario.evidence_kind]
    return Provenance(
        authority_class=scenario.authority_class,
        source_type=source_type,
        source_record_id=scenario.source_ref,
        retrieval_method=retrieval_method,
    )


def build_golden_proof_corpus() -> tuple[GoldenProofCase, ...]:
    cases: list[GoldenProofCase] = []
    for scenario in _SCENARIOS:
        for language_pair, premise_language, hypothesis_language in (
            ("IT_IT", "it", "it"),
            ("EN_IT", "en", "it"),
            ("EN_EN", "en", "en"),
        ):
            premise = scenario.premise_it if premise_language == "it" else scenario.premise_en
            hypothesis = (
                scenario.hypothesis_it
                if hypothesis_language == "it"
                else scenario.hypothesis_en
            )
            proof_unit = EvidenceProofUnit(
                proof_unit_id=f"golden:{scenario.key}:{premise_language}",
                authority_class=scenario.authority_class,
                evidence_kind=scenario.evidence_kind,
                scope=_scenario_scope(scenario),
                canonical_premise=premise,
                source_refs=[scenario.source_ref],
                provenance=_provenance(scenario),
                premise_language=premise_language,
                allowed_semantic_role=scenario.semantic_role,
                predicate=scenario.predicate,
                value=ProofValue(
                    canonical_values=list(scenario.canonical_values),
                    required_anchors=list(scenario.required_anchors),
                ),
            )
            cases.append(
                GoldenProofCase(
                    case_id=f"{scenario.key}:{language_pair.lower()}",
                    category=scenario.category,
                    language_pair=language_pair,
                    proof_unit=proof_unit,
                    hypothesis=hypothesis,
                    hypothesis_language=hypothesis_language,
                    expected_label=scenario.expected_label,
                    expected_accept=(
                        scenario.expected_label is EntailmentLabel.ENTAILMENT
                    ),
                    security_critical=scenario.security_critical,
                )
            )
    return tuple(cases)
