from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class PlaybookSignalRule:
    signal: str
    patterns: tuple[str, ...]
    source: str
    domain: str
    incident_types: tuple[str, ...]
    tags: tuple[str, ...]
    tactics: tuple[str, ...] = ()
    techniques: tuple[str, ...] = ()
    supporting_incident_types: tuple[str, ...] = ()
    supporting_tags: tuple[str, ...] = ()
    evidence_terms: tuple[str, ...] = ()
    priority: int = 0

    def matches(self, text: str) -> bool:
        return any(re.search(pattern, text, flags=re.IGNORECASE) for pattern in self.patterns)


def _rule(
    signal: str,
    patterns: tuple[str, ...],
    source: str,
    domain: str,
    incident_types: tuple[str, ...],
    tags: tuple[str, ...],
    *,
    tactics: tuple[str, ...] = (),
    techniques: tuple[str, ...] = (),
    supporting_incident_types: tuple[str, ...] = (),
    supporting_tags: tuple[str, ...] = (),
    evidence_terms: tuple[str, ...] = (),
) -> PlaybookSignalRule:
    priority = {
        "data_exfiltration": 100,
        "windows_host": 90,
        "linux_host": 85,
        "malware": 80,
        "network_suricata": 70,
        "dns": 60,
        "governance": 50,
    }.get(domain, 0)
    return PlaybookSignalRule(
        signal=signal,
        patterns=patterns,
        source=source,
        domain=domain,
        incident_types=incident_types,
        tags=tags,
        tactics=tactics,
        techniques=techniques,
        supporting_incident_types=supporting_incident_types,
        supporting_tags=supporting_tags,
        evidence_terms=evidence_terms or (signal.replace("_", " "),),
        priority=priority,
    )


# Ordered from more specific cross-domain scenarios to broader host and governance
# signals. The first matched rule supplies the primary source/domain; all matched
# rules contribute metadata candidates used for deterministic retrieval ranking.
EXPANDED_PLAYBOOK_SIGNAL_RULES = (
    _rule(
        "dns_based_exfiltration",
        (
            r"dns[_ -]based exfiltration",
            r"dns tunneling.{0,80}exfil",
            r"encoded dns (queries|labels).{0,80}(data|exfil)",
        ),
        "dns",
        "data_exfiltration",
        ("dns_based_exfiltration", "dns_tunneling_exfiltration", "covert_data_transfer"),
        ("exfiltration", "dns", "tunneling", "encoded-data", "covert-channel"),
        tactics=("Exfiltration",),
        techniques=("T1048", "T1071.004"),
    ),
    _rule(
        "large_data_transfer",
        (
            r"large (outbound )?data transfer",
            r"bulk outbound transfer",
            r"(unusual|excessive) upload volume",
        ),
        "suricata",
        "data_exfiltration",
        ("large_data_transfer", "bulk_outbound_transfer", "possible_data_exfiltration"),
        ("exfiltration", "large-transfer", "suricata", "data-loss", "outbound"),
        tactics=("Exfiltration",),
        techniques=("T1041", "T1048"),
    ),
    _rule(
        "unusual_external_destination",
        (
            r"unusual external destination",
            r"rare external destination",
            r"first[- ]seen external (domain|ip|destination)",
        ),
        "suricata",
        "data_exfiltration",
        ("unusual_external_destination", "rare_destination_contact", "possible_data_exfiltration"),
        ("exfiltration", "rare-destination", "suricata", "reputation", "outbound"),
        tactics=("Exfiltration", "Command and Control"),
        techniques=("T1041", "T1071"),
    ),
    _rule(
        "suspicious_outbound_connection",
        (
            r"suspicious outbound connection",
            r"unauthorized external connection",
            r"outbound connection.{0,80}(rare|suspicious|unapproved)",
        ),
        "suricata",
        "data_exfiltration",
        ("suspicious_outbound_connection", "possible_exfiltration", "unauthorized_external_connection"),
        ("exfiltration", "outbound", "suricata", "network", "external"),
        tactics=("Exfiltration", "Command and Control"),
        techniques=("T1041", "T1071"),
    ),
    _rule(
        "windows_successful_logon_after_failures",
        (
            r"windows[_ -]successful[_ -]logon[_ -]after[_ -]failures",
            r"(event( id)? )?4624.{0,100}(after|follow).{0,100}(4625|failed logon)",
            r"(4625|failed logon).{0,100}(followed by|then).{0,100}(4624|successful logon)",
        ),
        "wazuh",
        "windows_host",
        ("windows_successful_logon_after_failures", "possible_account_compromise", "credential_attack"),
        ("windows", "successful-logon", "failed-logon", "account-compromise", "event-4624", "event-4625"),
        tactics=("Initial Access", "Credential Access", "Lateral Movement"),
        techniques=("T1110", "T1078", "T1021.001"),
        supporting_incident_types=("windows_privileged_logon",),
    ),
    _rule(
        "windows_rdp_bruteforce",
        (
            r"windows[_ -]rdp[_ -]brute",
            r"rdp.{0,60}(brute[- ]?force|failed logon|password spray)",
            r"(4625|failed logon).{0,80}(logon type 10|rdp|remote desktop)",
        ),
        "wazuh",
        "windows_host",
        ("windows_rdp_bruteforce", "rdp_failed_logon", "credential_attack"),
        ("windows", "rdp", "brute-force", "authentication", "wazuh"),
        tactics=("Credential Access", "Initial Access"),
        techniques=("T1110", "T1021.001"),
    ),
    _rule(
        "windows_failed_logon",
        (
            r"windows[_ -]failed[_ -]logon",
            r"(event( id)? )?4625",
            r"windows authentication failure",
        ),
        "wazuh",
        "windows_host",
        ("windows_failed_logon", "repeated_failed_logon", "credential_attack"),
        ("windows", "failed-logon", "authentication", "event-4625", "wazuh"),
        tactics=("Credential Access",),
        techniques=("T1110",),
    ),
    _rule(
        "windows_privileged_logon",
        (
            r"windows[_ -]privileged[_ -]logon",
            r"(event( id)? )?4672",
            r"special privileges assigned to new logon",
        ),
        "wazuh",
        "windows_host",
        ("windows_privileged_logon", "privileged_account_access", "suspicious_admin_logon"),
        ("windows", "privileged-logon", "admin", "authentication", "wazuh"),
        tactics=("Initial Access", "Privilege Escalation"),
        techniques=("T1078",),
    ),
    _rule(
        "windows_local_admin_membership_change",
        (
            r"windows[_ -]local[_ -]admin[_ -]membership",
            r"(event( id)? )?4732",
            r"(member added|added member).{0,80}(administrators|local group)",
        ),
        "wazuh",
        "windows_host",
        ("windows_local_admin_membership_change", "privileged_group_change", "windows_privilege_change"),
        ("windows", "administrators-group", "privilege-change", "event-4732", "wazuh"),
        tactics=("Privilege Escalation", "Persistence"),
        techniques=("T1098",),
    ),
    _rule(
        "windows_new_user_created",
        (
            r"windows[_ -]new[_ -]user[_ -]created",
            r"(event( id)? )?4720",
            r"windows user account (was )?created",
        ),
        "wazuh",
        "windows_host",
        ("windows_new_user_created", "suspicious_account_creation", "windows_account_change"),
        ("windows", "user-created", "account-change", "event-4720", "wazuh"),
        tactics=("Persistence",),
        techniques=("T1136.001", "T1136.002"),
    ),
    _rule(
        "windows_encoded_powershell",
        (
            r"windows[_ -]encoded[_ -]powershell",
            r"powershell.{0,80}(-enc(odedcommand)?\b|frombase64string|base64)",
            r"encoded command.{0,80}powershell",
        ),
        "wazuh",
        "windows_host",
        ("windows_encoded_powershell", "obfuscated_command_execution", "possible_malware_execution"),
        ("windows", "powershell", "encoded-command", "obfuscation", "wazuh"),
        tactics=("Execution", "Defense Evasion"),
        techniques=("T1059.001", "T1027"),
        supporting_incident_types=("windows_suspicious_powershell",),
    ),
    _rule(
        "windows_suspicious_powershell",
        (
            r"windows[_ -]suspicious[_ -]powershell",
            r"powershell.{0,100}(invoke-expression|downloadstring|webclient|executionpolicy bypass)",
            r"(event( id)? )?4104.{0,100}(suspicious|malicious|download|bypass)",
        ),
        "wazuh",
        "windows_host",
        ("windows_suspicious_powershell", "suspicious_script_execution", "possible_malware_execution"),
        ("windows", "powershell", "script", "execution", "wazuh"),
        tactics=("Execution", "Defense Evasion"),
        techniques=("T1059.001", "T1027"),
    ),
    _rule(
        "windows_lolbin_execution",
        (
            r"windows[_ -]lolbin",
            r"\b(rundll32|regsvr32|mshta|certutil|bitsadmin|installutil|msbuild)\b.{0,100}(http|javascript|scriptlet|download|proxy execution)",
            r"living off the land binar",
        ),
        "wazuh",
        "windows_host",
        ("windows_lolbin_execution", "proxy_execution", "defense_evasion"),
        ("windows", "lolbin", "proxy-execution", "defense-evasion", "wazuh"),
        tactics=("Defense Evasion", "Execution"),
        techniques=("T1218", "T1105"),
    ),
    _rule(
        "windows_scheduled_task_persistence",
        (
            r"windows[_ -]scheduled[_ -]task[_ -]persistence",
            r"(event( id)? )?4698",
            r"scheduled task.{0,80}(created|persistence|highest privileges|system)",
        ),
        "wazuh",
        "windows_host",
        ("windows_scheduled_task_persistence", "scheduled_task_abuse", "windows_persistence"),
        ("windows", "scheduled-task", "persistence", "event-4698", "wazuh"),
        tactics=("Persistence", "Execution"),
        techniques=("T1053.005",),
    ),
    _rule(
        "windows_registry_run_key_persistence",
        (
            r"windows[_ -]registry[_ -]run[_ -]key",
            r"registry.{0,80}(runonce|run key|winlogon).{0,80}(persistence|autorun|startup)",
            r"(sysmon )?event( id)? (12|13|14).{0,80}(runonce|run key|winlogon)",
        ),
        "wazuh",
        "windows_host",
        ("windows_registry_run_key_persistence", "registry_persistence", "windows_persistence"),
        ("windows", "registry", "run-key", "persistence", "wazuh"),
        tactics=("Persistence",),
        techniques=("T1060", "T1112"),
    ),
    _rule(
        "windows_service_creation",
        (
            r"windows[_ -]service[_ -]creation",
            r"(event( id)? )?(7045|4697)",
            r"windows service.{0,80}(installed|created|remote execution)",
        ),
        "wazuh",
        "windows_host",
        ("windows_service_creation", "remote_service_execution", "windows_persistence"),
        ("windows", "service-creation", "persistence", "event-7045", "wazuh"),
        tactics=("Persistence", "Privilege Escalation", "Lateral Movement"),
        techniques=("T1543.003", "T1021"),
    ),
    _rule(
        "windows_lateral_movement_smb",
        (
            r"windows[_ -]lateral[_ -]movement[_ -]smb",
            r"(admin\$|c\$|ipc\$).{0,100}(lateral|remote|service|executable)",
            r"(event( id)? )?(5140|5145).{0,100}(admin share|lateral|smb)",
        ),
        "wazuh",
        "windows_host",
        ("windows_lateral_movement_smb", "admin_share_access", "network_logon_lateral_movement"),
        ("windows", "smb", "lateral-movement", "admin-share", "wazuh"),
        tactics=("Lateral Movement",),
        techniques=("T1021.002",),
    ),
    _rule(
        "windows_security_log_cleared",
        (
            r"windows[_ -]security[_ -]log[_ -]cleared",
            r"(event( id)? )?1102",
            r"(security|windows event) log (was )?cleared",
        ),
        "wazuh",
        "windows_host",
        ("windows_security_log_cleared", "anti_forensics", "possible_compromise"),
        ("windows", "security-log-cleared", "anti-forensics", "event-1102", "wazuh"),
        tactics=("Defense Evasion",),
        techniques=("T1070.001",),
    ),
    _rule(
        "windows_defender_tampering",
        (
            r"windows[_ -]defender[_ -]tamper",
            r"(defender|set-mppreference).{0,100}(disabled|exclusion|tamper|real-time protection)",
            r"(event( id)? )?5007",
        ),
        "wazuh",
        "windows_host",
        ("windows_defender_tampering", "endpoint_protection_disabled", "defense_evasion"),
        ("windows", "defender", "tampering", "defense-evasion", "wazuh"),
        tactics=("Defense Evasion",),
        techniques=("T1562.001",),
    ),
    _rule(
        "windows_sysmon_suspicious_process",
        (
            r"sysmon\s*-\s*suspicious process",
            r"sysmon_process[-_ ]anomal",
            r"suspicious process.{0,100}explorer\.exe",
        ),
        "wazuh",
        "windows_host",
        (
            "windows_sysmon_suspicious_process",
            "suspicious_process_execution",
            "process_anomaly",
        ),
        ("windows", "sysmon", "process", "process-anomaly", "event-1", "wazuh"),
        tactics=("Defense Evasion", "Privilege Escalation"),
        techniques=("T1055",),
        evidence_terms=(
            "Sysmon Event ID 1 suspicious process ancestry, image and command line",
        ),
    ),
    _rule(
        "windows_netsh_firewall_rule_change",
        (
            r"netsh used to (add|delete|modify) firewall rule",
            r"netsh(\.exe)?.{0,160}advfirewall.{0,160}firewall.{0,80}(add|delete|set) rule",
            r"disable or modify system firewall.{0,80}t1562\.004",
        ),
        "wazuh",
        "windows_host",
        (
            "windows_netsh_firewall_rule_change",
            "windows_firewall_configuration_change",
            "defense_evasion",
        ),
        ("windows", "netsh", "firewall", "rule-change", "defense-evasion", "wazuh"),
        tactics=("Defense Evasion",),
        techniques=("T1562.004",),
        evidence_terms=(
            "netsh advfirewall command creates, modifies or deletes a Windows Firewall rule",
        ),
    ),
    _rule(
        "windows_cis_benchmark_failure",
        (
            r"cis microsoft windows .{0,80} benchmark",
            r"security configuration assessment.{0,80}(failed|failure)",
            r"data.{0,20}sca.{0,240}check.{0,240}result.{0,40}failed",
        ),
        "wazuh",
        "windows_host",
        (
            "windows_cis_benchmark_failure",
            "windows_security_configuration_gap",
            "compliance_finding",
        ),
        ("windows", "cis", "sca", "benchmark", "compliance", "hardening", "wazuh"),
        evidence_terms=(
            "Wazuh SCA reports a failed CIS Microsoft Windows benchmark check",
        ),
    ),
    _rule(
        "reverse_shell_detection",
        (
            r"reverse shell",
            r"(netcat|nc|socat|bash|powershell|python).{0,100}(socket|tcp|connect).{0,100}(shell|stdin|stdout)",
            r"interactive remote shell",
        ),
        "wazuh",
        "malware",
        ("reverse_shell_detection", "interactive_remote_shell", "command_and_control_shell"),
        ("malware", "reverse-shell", "interactive-shell", "c2", "wazuh"),
        tactics=("Execution", "Command and Control"),
        techniques=("T1059", "T1071"),
    ),
    _rule(
        "suspicious_download_execution",
        (
            r"suspicious download.{0,80}execution",
            r"download(ed)? payload.{0,80}execut",
            r"(curl|wget|certutil|bitsadmin|downloadstring).{0,120}(chmod|exec|start-process|rundll32|powershell)",
        ),
        "wazuh",
        "malware",
        ("suspicious_download_execution", "ingress_tool_transfer", "downloaded_payload_execution"),
        ("malware", "download", "execution", "payload", "wazuh"),
        tactics=("Command and Control", "Execution"),
        techniques=("T1105", "T1204"),
    ),
    _rule(
        "encoded_command_execution",
        (
            r"encoded command execution",
            r"obfuscated command execution",
            r"(base64|frombase64string|xxd|certutil).{0,100}(decode|execute|shell|powershell)",
        ),
        "wazuh",
        "malware",
        ("encoded_command_execution", "obfuscated_command_execution", "possible_malware_execution"),
        ("malware", "encoded-command", "obfuscation", "execution", "wazuh"),
        tactics=("Execution", "Defense Evasion"),
        techniques=("T1059", "T1027"),
    ),
    _rule(
        "suspicious_script_execution",
        (
            r"suspicious script execution",
            r"(powershell|python|perl|javascript|vbscript|wscript|cscript).{0,100}(suspicious|download|payload|bypass)",
            r"script interpreter abuse",
        ),
        "wazuh",
        "malware",
        ("suspicious_script_execution", "script_interpreter_abuse", "possible_malware_execution"),
        ("malware", "script", "powershell", "shell", "execution", "wazuh"),
        tactics=("Execution",),
        techniques=("T1059",),
    ),
    _rule(
        "malware_suspicious_execution",
        (
            r"malware[_ -]suspicious[_ -]execution",
            r"(malicious|suspicious|unknown|unsigned) (binary|process|executable).{0,80}(execut|launch|started)",
            r"possible endpoint compromise.{0,80}(process|execution|malware)",
        ),
        "wazuh",
        "malware",
        ("malware_suspicious_execution", "suspicious_process_execution", "possible_endpoint_compromise"),
        ("malware", "process-execution", "endpoint", "wazuh"),
        tactics=("Execution", "Defense Evasion"),
        techniques=("T1059", "T1204"),
    ),
    _rule(
        "unauthorized_user_creation",
        (
            r"unauthorized (linux )?user creation",
            r"\b(useradd|adduser)\b.{0,100}(unexpected|unauthorized|suspicious|uid 0)",
            r"/etc/passwd.{0,80}(new user|account created|modified)",
        ),
        "wazuh",
        "linux_host",
        ("unauthorized_user_creation", "suspicious_account_creation", "linux_account_change"),
        ("linux", "user-creation", "account-change", "wazuh"),
        tactics=("Persistence",),
        techniques=("T1136.001",),
    ),
    _rule(
        "user_group_membership_change",
        (
            r"(linux )?(user )?group membership change",
            r"\b(usermod|gpasswd)\b.{0,100}(sudo|wheel|docker|lxd|adm|shadow)",
            r"(added|membership).{0,80}(sudo|wheel|privileged group)",
        ),
        "wazuh",
        "linux_host",
        ("user_group_membership_change", "privileged_group_change", "linux_privilege_change"),
        ("linux", "group-membership", "privilege-change", "sudo", "wazuh"),
        tactics=("Privilege Escalation", "Persistence"),
        techniques=("T1098",),
    ),
    _rule(
        "sensitive_file_modification",
        (
            r"sensitive (linux )?file modification",
            r"/etc/(passwd|shadow|sudoers|ssh/sshd_config)",
            r"authorized_keys.{0,80}(modified|changed|added)",
        ),
        "wazuh",
        "linux_host",
        ("sensitive_file_modification", "linux_configuration_tampering", "credential_file_change"),
        ("linux", "fim", "passwd", "sudoers", "ssh", "wazuh"),
        tactics=("Persistence", "Privilege Escalation", "Defense Evasion"),
        techniques=("T1098", "T1112"),
    ),
    _rule(
        "suspicious_cron_job",
        (
            r"suspicious (linux )?cron",
            r"/etc/cron(d|tab)?",
            r"\bcrontab\b.{0,100}(curl|wget|/tmp|/dev/shm|reverse shell|encoded)",
        ),
        "wazuh",
        "linux_host",
        ("suspicious_cron_job", "cron_persistence", "scheduled_execution"),
        ("linux", "cron", "scheduled-task", "persistence", "wazuh"),
        tactics=("Persistence", "Execution"),
        techniques=("T1053.003",),
    ),
    _rule(
        "suspicious_binary_execution_tmp",
        (
            r"suspicious[_ -]binary[_ -]execution[_ -](tmp|temporary)",
            r"suspicious binary execution.{0,80}(temporary|/tmp|/var/tmp|/dev/shm)",
            r"(executed|execution|process).{0,80}(/tmp|/var/tmp|/dev/shm)",
            r"temporary path execution",
        ),
        "wazuh",
        "linux_host",
        ("suspicious_binary_execution_tmp", "temporary_path_execution", "possible_malware_execution"),
        ("linux", "temporary-path", "binary-execution", "malware", "wazuh"),
        tactics=("Execution", "Defense Evasion"),
        techniques=("T1059", "T1204"),
    ),
    _rule(
        "shell_history_tampering",
        (
            r"shell history tamper",
            r"(history -c|unset histfile|histsize=0)",
            r"\.(bash|zsh)_history.{0,80}(deleted|cleared|truncated|modified)",
        ),
        "wazuh",
        "linux_host",
        ("shell_history_tampering", "anti_forensics", "indicator_removal"),
        ("linux", "shell-history", "anti-forensics", "defense-evasion", "wazuh"),
        tactics=("Defense Evasion",),
        techniques=("T1070",),
    ),
    _rule(
        "linux_persistence_mechanism",
        (
            r"linux persistence mechanism",
            r"(/etc/ld\.so\.preload|pam module|kernel module).{0,100}(persistence|modified|created)",
            r"(systemd|cron|authorized_keys|shell profile).{0,100}multiple persistence",
        ),
        "wazuh",
        "linux_host",
        ("linux_persistence_mechanism", "unauthorized_persistence", "post_compromise_persistence"),
        ("linux", "persistence", "systemd", "cron", "ssh", "wazuh"),
        tactics=("Persistence", "Privilege Escalation"),
        techniques=("T1053.003", "T1543.002", "T1098"),
    ),
    _rule(
        "suricata_c2_beaconing",
        (
            r"suricata.{0,100}(c2|command and control).{0,80}beacon",
            r"suricata_c2_beaconing",
            r"suricata.{0,100}periodic (callback|connection|traffic)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_c2_beaconing", "network_beaconing", "command_and_control"),
        ("suricata", "c2", "beaconing", "network", "command-and-control"),
        tactics=("Command and Control",),
        techniques=("T1071",),
    ),
    _rule(
        "suricata_malware_callback",
        (
            r"suricata.{0,100}malware callback",
            r"suricata_malware_callback",
            r"(suricata|et malware).{0,100}(callback|botnet|compromised host)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_malware_callback", "malicious_outbound_connection", "possible_malware_infection"),
        ("suricata", "malware", "callback", "outbound", "c2"),
        tactics=("Command and Control",),
        techniques=("T1071", "T1105"),
    ),
    _rule(
        "suricata_exploit_attempt",
        (
            r"suricata.{0,100}exploit attempt",
            r"suricata_exploit_attempt",
            r"(suricata|et exploit).{0,100}(cve|shellcode|injection|traversal)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_exploit_attempt", "network_exploitation", "public_facing_exploit"),
        ("suricata", "exploit", "vulnerability", "initial-access", "network"),
        tactics=("Initial Access",),
        techniques=("T1190",),
    ),
    _rule(
        "suricata_http_suspicious_request",
        (
            r"suricata.{0,100}suspicious http request",
            r"suricata_http_suspicious_request",
            r"(suricata|et web).{0,100}(http|uri|user agent).{0,80}(suspicious|malicious|injection)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_http_suspicious_request", "web_attack", "suspicious_http_activity"),
        ("suricata", "http", "web-attack", "request", "network"),
        tactics=("Initial Access", "Command and Control"),
        techniques=("T1190", "T1071.001"),
    ),
    _rule(
        "suricata_tls_anomaly",
        (
            r"suricata.{0,100}tls anomaly",
            r"suricata_tls_anomaly",
            r"(suricata|tls).{0,100}(ja3|ja4|self-signed|certificate anomaly|sni anomaly)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_tls_anomaly", "suspicious_encrypted_channel", "certificate_anomaly"),
        ("suricata", "tls", "certificate", "encrypted-channel", "network"),
        tactics=("Command and Control",),
        techniques=("T1573",),
    ),
    _rule(
        "suricata_lateral_movement",
        (
            r"suricata.{0,100}lateral movement",
            r"suricata_lateral_movement",
            r"suricata.{0,100}(east-west|remote service).{0,80}(suspicious|lateral)",
        ),
        "suricata",
        "network_suricata",
        ("suricata_lateral_movement", "east_west_suspicious_traffic", "remote_service_activity"),
        ("suricata", "lateral-movement", "east-west", "remote-services", "network"),
        tactics=("Lateral Movement",),
        techniques=("T1021",),
    ),
    _rule(
        "newly_registered_domain",
        (
            r"newly registered domain",
            r"recently registered domain",
            r"domain age.{0,40}(new|recent|[0-9]+ day)",
        ),
        "dns",
        "dns",
        ("newly_registered_domain", "suspicious_domain_contact", "possible_command_and_control"),
        ("dns", "newly-registered-domain", "domain-reputation", "c2"),
        tactics=("Command and Control",),
        techniques=("T1071.004",),
    ),
    _rule(
        "high_entropy_domain",
        (
            r"high entropy (domain|dns|label|subdomain)",
            r"random[- ]looking (domain|dns|label|subdomain)",
            r"base64[- ]like dns",
        ),
        "dns",
        "dns",
        ("high_entropy_domain", "suspicious_dns_label", "possible_dns_tunneling"),
        ("dns", "high-entropy", "encoded-label", "tunneling"),
        tactics=("Command and Control", "Exfiltration"),
        techniques=("T1071.004", "T1048"),
    ),
    _rule(
        "domain_generation_algorithm",
        (
            r"domain generation algorithm",
            r"\bdga\b.{0,80}(domain|dns|nxdomain|malware)",
            r"algorithmically generated domain",
        ),
        "dns",
        "dns",
        ("domain_generation_algorithm", "dga_activity", "malware_domain_generation"),
        ("dns", "dga", "malware", "algorithmic-domain", "c2"),
        tactics=("Command and Control",),
        techniques=("T1568.002", "T1071.004"),
    ),
    _rule(
        "excessive_dns_volume",
        (
            r"excessive dns (volume|queries|traffic)",
            r"dns query (spike|flood|surge)",
            r"abnormal dns (query rate|volume)",
        ),
        "dns",
        "dns",
        ("excessive_dns_volume", "dns_query_spike", "possible_dns_abuse"),
        ("dns", "volume", "query-spike", "tunneling", "resolver"),
        tactics=("Command and Control", "Exfiltration"),
        techniques=("T1071.004", "T1048"),
    ),
    _rule(
        "severity_classification",
        (
            r"severity classification",
            r"incident priority review",
            r"(change|review|classify).{0,60}(severity|priority).{0,60}(evidence|impact|risk)",
        ),
        "internal_policy",
        "governance",
        ("severity_classification", "incident_priority_review", "risk_classification"),
        ("governance", "severity", "risk", "human-review", "decision-support"),
    ),
    _rule(
        "case_escalation",
        (
            r"case escalation",
            r"incident to case",
            r"(open|create|escalate).{0,60}(investigation )?case",
        ),
        "internal_policy",
        "governance",
        ("case_escalation", "incident_to_case", "multi_incident_investigation"),
        ("governance", "case", "escalation", "workflow", "human-review"),
    ),
    _rule(
        "evidence_collection_standard",
        (
            r"evidence collection standard",
            r"forensic evidence quality",
            r"(collect|preserve).{0,60}(evidence|artifact).{0,60}(integrity|provenance|chain of custody)",
        ),
        "internal_policy",
        "governance",
        ("evidence_collection_standard", "forensic_evidence_quality", "investigation_documentation"),
        ("governance", "evidence", "audit", "chain-of-custody", "human-review"),
    ),
    _rule(
        "wazuh_agent_queue_saturation",
        (
            r"agent event queue is (90% )?full",
            r"agent event queue is flooded",
            r"agent buffer.{0,40}(90%|full|flooded)",
            r"agent_flooding",
        ),
        "wazuh",
        "governance",
        (
            "wazuh_agent_queue_saturation",
            "telemetry_loss_risk",
            "agent_health_degradation",
        ),
        ("wazuh", "agent", "queue", "buffer", "telemetry-loss", "service-health"),
        evidence_terms=(
            "Wazuh agent event buffer is near capacity, full or flooded",
        ),
    ),
    _rule(
        "containment_approval",
        (
            r"containment approval",
            r"remediation authorization",
            r"(approve|approval).{0,60}(isolate|block|disable account|revoke session|containment)",
        ),
        "internal_policy",
        "governance",
        ("containment_approval", "remediation_authorization", "defensive_action_review"),
        ("governance", "containment", "approval", "risk", "human-review"),
    ),
    _rule(
        "post_incident_review",
        (
            r"post[- ]incident review",
            r"lessons learned",
            r"case retrospective",
        ),
        "internal_policy",
        "governance",
        ("post_incident_review", "lessons_learned", "case_retrospective"),
        ("governance", "post-incident", "lessons-learned", "closure", "human-review"),
    ),
)


EXPANDED_PLAYBOOK_PRIMARY_INCIDENT_TYPES = frozenset(
    rule.incident_types[0] for rule in EXPANDED_PLAYBOOK_SIGNAL_RULES
)
