"""Structured investigation domain models for v0.6 workflows."""

from .adapters import (
    InvestigationContext,
    context_from_command_room_payload,
    context_from_incident_ai_payload,
    evidence_references_from_context,
    normalize_existing_ai_analysis,
    normalize_investigation_context,
)
from .confidence import calculate_confidence, calculate_hypothesis_confidence
from .engine import InvestigationLlmClient, generate_investigation_brief
from .evidence import (
    EvidenceNormalizationResult,
    evidence_by_type,
    has_ioc_evidence,
    normalize_evidence,
    normalize_evidence_references,
)
from .expansion import (
    InvestigationExpansionResult,
    build_candidate_evidence,
    missing_evidence_from_brief,
    run_single_enrichment_pass,
)
from .factory import create_empty_investigation_brief, create_fallback_investigation_brief
from .models import (
    ConfidenceAssessment,
    EvidenceReference,
    InvestigationBrief,
    InvestigationClaimClassification,
    InvestigationConfidenceLevel,
    InvestigationEvidenceStrength,
    InvestigationEvidenceType,
    InvestigationFinding,
    InvestigationFindingType,
    InvestigationHypothesis,
    InvestigationHypothesisStatus,
    InvestigationLimitation,
    InvestigationSession,
    InvestigationSessionStatus,
    RecommendedAction,
    RecommendedActionApprovalRequirement,
    RecommendedActionCategory,
    RecommendedCheck,
    RecommendedCheckPriority,
)
from .persistence import (
    InvestigationPersistenceResult,
    InvestigationPersistenceStore,
    InvestigationSessionHistoryItem,
    InvestigationSnapshotSummary,
    deserialize_investigation_brief,
    safe_persist_investigation_brief,
    serialize_investigation_brief,
)
from .prompts import INVESTIGATION_SYSTEM_PROMPT, build_investigation_prompt
from .reasoning import (
    ReasoningAssessment,
    analyze_reasoning_context,
    classify_hypothesis_claim,
    detect_contradictions,
    identify_missing_evidence,
)
from .retrieval import (
    InvestigationEvidenceExpansion,
    InvestigationRetrievalContext,
    InvestigationRetrievalLimits,
    InvestigationRetrievalPriority,
    InvestigationRetrievalRequest,
    InvestigationRetrievalResult,
    InvestigationRetrievalStatus,
    InvestigationRetrievalType,
    build_retrieval_requests,
    execute_retrieval_request,
    prioritize_retrieval_requests,
    run_bounded_retrieval,
)
from .validators import (
    InvestigationValidationIssue,
    assert_valid_investigation_brief,
    contains_unqualified_certainty,
    normalize_confidence_score,
    validate_investigation_brief,
    validate_investigation_session,
    validate_recommended_action,
)

__all__ = [
    "ConfidenceAssessment",
    "EvidenceNormalizationResult",
    "EvidenceReference",
    "INVESTIGATION_SYSTEM_PROMPT",
    "InvestigationContext",
    "InvestigationEvidenceExpansion",
    "InvestigationExpansionResult",
    "InvestigationBrief",
    "InvestigationClaimClassification",
    "InvestigationConfidenceLevel",
    "InvestigationEvidenceStrength",
    "InvestigationEvidenceType",
    "InvestigationFinding",
    "InvestigationFindingType",
    "InvestigationHypothesis",
    "InvestigationHypothesisStatus",
    "InvestigationLimitation",
    "InvestigationPersistenceResult",
    "InvestigationPersistenceStore",
    "InvestigationSession",
    "InvestigationSessionHistoryItem",
    "InvestigationSessionStatus",
    "InvestigationSnapshotSummary",
    "InvestigationValidationIssue",
    "InvestigationLlmClient",
    "InvestigationRetrievalContext",
    "InvestigationRetrievalLimits",
    "InvestigationRetrievalPriority",
    "InvestigationRetrievalRequest",
    "InvestigationRetrievalResult",
    "InvestigationRetrievalStatus",
    "InvestigationRetrievalType",
    "RecommendedAction",
    "RecommendedActionApprovalRequirement",
    "RecommendedActionCategory",
    "RecommendedCheck",
    "RecommendedCheckPriority",
    "ReasoningAssessment",
    "analyze_reasoning_context",
    "assert_valid_investigation_brief",
    "build_candidate_evidence",
    "build_investigation_prompt",
    "build_retrieval_requests",
    "calculate_confidence",
    "calculate_hypothesis_confidence",
    "classify_hypothesis_claim",
    "contains_unqualified_certainty",
    "context_from_command_room_payload",
    "context_from_incident_ai_payload",
    "create_empty_investigation_brief",
    "create_fallback_investigation_brief",
    "detect_contradictions",
    "deserialize_investigation_brief",
    "evidence_by_type",
    "evidence_references_from_context",
    "execute_retrieval_request",
    "generate_investigation_brief",
    "has_ioc_evidence",
    "identify_missing_evidence",
    "missing_evidence_from_brief",
    "normalize_confidence_score",
    "normalize_evidence",
    "normalize_evidence_references",
    "normalize_existing_ai_analysis",
    "normalize_investigation_context",
    "prioritize_retrieval_requests",
    "run_bounded_retrieval",
    "run_single_enrichment_pass",
    "safe_persist_investigation_brief",
    "serialize_investigation_brief",
    "validate_investigation_brief",
    "validate_investigation_session",
    "validate_recommended_action",
]
